baseurl = "http://cupe1974.ca"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = "7"
theme = "mainroad"
title = "CUPE 1974"
[Author]
avatar = "img/avatar.png"
bio = "Kingston Hospital Workers are a local of the Canadian Union of Public Employees (CUPE), Canada's largest healthcare union."
name = "CUPE 1974"
[params]
authorbox = true
description = "CUPE Local 1974 is Kingston's Hospital Workers union."
leftsidebar = false
opengraph = true
post_navigation = true
postsections = ["post"]
readmore = false
subtitle = "Kingston's Hospital Workers"
[params.widgets]
categories = true
recent_articles = true
search = true
tags = true
tags_counter = true
